### ISSUE TITLE
Section Article List

### ISSUE THREAD

**Issue by lauracastrovenegas** [spectatorpublishing/eye-space-issue#6]
## Background
**Task:** Make the list of articles for each section.

File to work on: [`Section.js`](https://github.com/spectatorpublishing/eye-space-issue/blob/a3c78ce1c85b83595738594d8a266ccc46dff337/src/containers/Section.js)

## Mockups
[Figma Mockup](https://www.figma.com/file/W4Ztx8hkUId6TLIRP3aBSG/Space-Edition?node-id=0%3A1)

**Desktop**

Component
<img width="216" alt="Screen Shot 2022-08-28 at 7 41 02 PM" src="https://user-images.githubusercontent.com/61126997/187099946-83879551-42b3-4c5e-855b-6fbd6d01d17f.png">

Screen
<img width="798" alt="Screen Shot 2022-08-28 at 7 40 45 PM" src="https://user-images.githubusercontent.com/61126997/187099937-95a23cfe-0f6f-41e3-b8f5-708fd47f4153.png">

**Mobile**
Component
<img width="251" alt="Screen Shot 2022-08-28 at 7 53 31 PM" src="https://user-images.githubusercontent.com/61126997/187099985-6e045614-2c4a-450a-8330-473b27bb7ab1.png">

Screen
<img width="250" alt="Screen Shot 2022-08-28 at 7 53 26 PM" src="https://user-images.githubusercontent.com/61126997/187099977-d46cb0a4-c4ee-4ce1-8382-fb0d0f4603fd.png">

**Comment by yuchenxhuang** [comment]
## Desktop
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69815463/187486911-5f0488c3-63b3-4f01-bb0b-4e42e787f133.png">

## Mobile
<img width="358" alt="image" src="https://user-images.githubusercontent.com/69815463/187487408-9e2ca49e-aa7e-4abb-9d0b-88080eedf265.png">
